### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by vanatteveldt** [ixa-ehu/ixa-pipe-tok#6]
When I compile and run the newest version I get the following error:
```{sh}
$ java -jar $MDIR/ixa-pipe-tok/target/ixa-pipe-tok-1.8.5.jar tok -l nl
no main manifest attribute, in /data/wva/newsreader_pipe_nl/modules/ixa-pipe-tok/target/ixa-pipe-tok-1.8.5.jar
```

**Comment by ragerri** [comment]
Hi,

You have to use now the exec binary in the target directory.

ixa-pipe-tok-1.8.5-exec.jar

R

**Comment by vanatteveldt** [comment]
Thanks, that works. I created a small pull request to update the README.md (https://github.com/ixa-ehu/ixa-pipe-tok/pull/7)
