### ISSUE TITLE
System.err.printf without DEBUG?

### ISSUE THREAD

**Issue by danielnaber** [ixa-ehu/ixa-pipe-tok#8]
At https://github.com/ixa-ehu/ixa-pipe-tok/blob/99f13feb657dccf48658c8021592867ae602094a/src/main/java/eus/ixa/ixa/pipe/tok/RuleBasedTokenizer.java#L245 there's a `System.err.printf` and it seems to me the `if (DEBUG) {}` around it is missing?

**Comment by ragerri** [comment]
It is done like that on purpose. Thanks
